[package]
name = "grok_multiverse"
version = "0.1.0"
description = "Created with Solana Playground"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "grok_multiverse"

[dependencies]
anchor-lang = "0.29.0"
